name: blasr
description: Run blasr on sequenced reads
keywords:
    - sequence alignment
    - long reads
    - fastq
tools:
    - blasr:
        description: |
        BLASR (Basic Local Alignment with Successive Refinement) for mapping
        Single Molecule Sequencing (SMS) reads that are thousands of bases long,
        with divergence between the read and genome dominated by insertion and
        deletion error.
        homepage: https://github.com/PacificBiosciences/blasr
        documentation: https://github.com/PacificBiosciences/blasr/wiki
        licence: https://www.pacb.com/legal-and-trademarks/software-end-user-license-agreement/
input:
    - meta:
        type: map
        description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
    - reads:
        type: file
        description: |
            List of input FastQ files of size 1 and 2 for single-end and paired-end data,
            respectively.
output:
    - meta:
        type: map
        description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
    - bam:
        type: file
        description: Alignment file
        pattern: "*bam"
    - versions:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
authors:
    - "@chelauk"
